### ISSUE TITLE
nautilus fails to transfer file by dragging

### ISSUE THREAD

**Issue by isntism** [theWebalyst/safenetwork-fuse#18]
OS: Ubuntu 18.04
Peruse: peruse-v0.7.0-linux-x64
nautilus: nautilus 1:3.26.4-0~ubuntu18.04.2
Safe-Drive: git/development

Problem: When dragging a file from one nautilus page to another it starts moving the file, which seems to work as expected but then nautilus says 0 files transfered and you have to look in the suddenly created `es` folder to find the original file.

steps: Mount safe-drive, open two nautilus instances, set both to the folders you need, drag the file you want to transfer to the other nautilus instance, get confused from the suddenly created folder named 'es'

logcommand: DEBUG=safe-fuse:ops*,safe-fuse:stubs*,safe-fuse:vfs-cache*,safe-vfs:*,safenetworkjs:containers*,safenetworkjs:cache*,safenetworkjs:file* node bin.js 2>&1 | tee nautilus-move-file.log

[nautilus-move-file.log](https://github.com/theWebalyst/safenetwork-fuse/files/2613066/nautilus-move-file.log)

**Comment by happybeing** [comment]
Thank you @isntism, that's an examplary bug report. I appreciate you effort in testing and collecting together the info needed to investigate it.

I'm linking here to the original post on the forum, which mentions the specific directories involved. They will be apparent from the log, but this will help me locate them in there:

https://forum.safedev.org/t/safe-drive-help-with-testing/2019/176?u=happybeing

**Comment by happybeing** [comment]
Closing in favour of [issue #9](https://github.com/theWebalyst/safe-drive/issues/9) in [new SAFE Drive repo](https://github.com/theWebalyst/safe-drive) as this repo is no longer in use.
