### ISSUE TITLE
Error: Could not locate the bindings file.

### ISSUE THREAD

**Issue by happybeing** [theWebalyst/safenetwork-fuse#3]
```
bartek@bartek-pc ~/Pobrane/safenetwork-fuse-v0.1.0-linux-x64
$ ./mount-safe 
pkg/prelude/bootstrap.js:1176
      throw error;
      ^

Error: Could not locate the bindings file. Tried:
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/build/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/build/Debug/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/build/Release/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/out/Debug/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/Debug/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/out/Release/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/Release/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/build/default/weakref.node
 → /snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/compiled/8.11.3/linux/x64/weakref.node
    at bindings (/snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/snapshot/safenetwork-fuse/node_modules/safenetworkjs/node_modules/weak/lib/weak.js:7:35)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)
```

_Originally posted by @bm371613 in https://github.com/theWebalyst/safenetwork-fuse/issues/1#issuecomment-421261035_

**Comment by happybeing** [comment]
@bm371613 please can you provide some info, the output from these commands:

`cat /proc/version`

and (the -s prevents any changes, this is just to see if you have these packages):

`apt-get -s install libfuse2 libfuse-dev xdg-utils`

Thanks for trying this out and taking the time to post your results, it helps a lot :+1:

**Comment by bm371613** [comment]
I'm using Manjaro (Arch-based distro), hopefully this is just as helpful:
```
bartek@bartek-pc ~
$ cat /proc/version
Linux version 4.14.69-1-MANJARO (builduser@development) (gcc version 8.2.1 20180831 (GCC)) #1 SMP PREEMPT Mon Sep 10 02:18:25 UTC 2018
[I] duration: 0.002s status: 0
bartek@bartek-pc ~
$ pacman -Qs fuse
local/exfat-utils 1.2.8-1
    Utilities for exFAT file system
local/fuse-common 3.2.5-1
    Common files for fuse2/3 packages
local/fuse2 2.9.8-1
    A library that makes it possible to implement a filesystem in a userspace program.
local/fuse3 3.2.5-1
    A library that makes it possible to implement a filesystem in a userspace program.
local/mtpfs 1.1-3
    A FUSE filesystem that supports reading and writing from any MTP device
local/sshfs 3.5.0-1
    FUSE client based on the SSH File Transfer Protocol
[I] duration: 0.027s status: 0
bartek@bartek-pc ~
$ pacman -Qs xdg-utils
local/xdg-utils 1.1.3-3
    Command line tools that assist applications with a variety of desktop integration tasks
[I] duration: 0.027s status: 0
```

**Comment by bm371613** [comment]
You can see I have `xdg-utils 1.1.3-3` and `fuse2 2.9.8-1`. The contents of `libfuse-dev` are probably a part of `fuse2` as explained [here](https://unix.stackexchange.com/questions/28972/why-are-there-no-dev-packages-in-arch-linux).

**Comment by happybeing** [comment]
Here's an updated build which you might find works. Fingers crossed for rc2:

https://github.com/theWebalyst/safenetwork-fuse/blob/dev-safenodeapp-v8/releases/safenetwork-fuse-v0.1.0-rc2-linux-x64.zip

**Comment by bm371613** [comment]
I fails differently now

```
$ ./mount-safe 
Server path not specified, so defaulting to ipc.config.socketRoot + ipc.config.appspace + ipc.config.id /tmp/app.3455
starting server on  /tmp/app.3455 
starting TLS server false
starting server as Unix || Windows Socket
## socket connection to server detected ##
received event of :  auth-uri { id: '3455-cli',
  message: 'safe-c2fmzw5ldhdvcmstznvzzq:AQAAAARkBfsAAAAAAAAAACAAAAAAAAAABqqm-pcNmgBEcgxVOasl1ryJU5Y_Oln1WWhXjrHiV88gAAAAAAAAAB5dIGphLDQNf0FQ0HT4JLRxtG9cy3xu4kaWKbOD8pZjIAAAAAAAAADefEPn_b9K0uL9Y-zDUVDVJgrcano8Ry8LjajAcWyDkkAAAAAAAAAAHGqeWoEedqG8NPbMRdoi4_hvimMp4jsh9mG7smQPPyjefEPn_b9K0uL9Y-zDUVDVJgrcano8Ry8LjajAcWyDkiAAAAAAAAAAcuE-ns3WzZ3nl0X2zf0tLJF-Zhusf7uWpT_dFJDJHXcgAAAAAAAAAFKhqh7zZROqcxVVuW99l1i7-je85dremyKSB36yKEIBAAAAAAAAAAAAAAAAAAAAAOtGsK0Epia4pp8f8ihdxcOl9MEE9whHX95vm1OtxC8hmDoAAAAAAAAYAAAAAAAAAJf1GHO_7fnqj4IuRP7OOKF_QxosPkIojQIAAAAAAAAADAAAAAAAAABfcHVibGljTmFtZXPHzemCA7eYygVC5zmwjao54Q0rBQ5pso1jQIGH2MTUAJg6AAAAAAAAASAAAAAAAAAARKNpBxBKSl9ez_BdEam5qibFLkS5Jm4a2eyO6KvQcAoYAAAAAAAAABqiSCPJYjv7wcO51e-fchm7XlUXg5bwIQAEAAAAAAAAAAAAAAABAAAAAgAAAAMAAAAHAAAAAAAAAF9wdWJsaWOixDS2iKEqhlWp5oUJt-iI8yv66pibaDrhv-kpSXnsf5g6AAAAAAAAAAAEAAAAAAAAAAAAAAABAAAAAgAAAAMAAAA' }
socket disconnected 3455-cli
(node:3455) UnhandledPromiseRejectionWarning: Error: SafeContainer initialise failed: _public (Cannot read property 'getContainer' of undefined)
    at PublicContainer.initialise (/snapshot/safenetwork-fuse/node_modules/safenetworkjs/src/safe-containers.js:0:0)
    at SafenetworkApi.getSafeContainer (/snapshot/safenetwork-fuse/node_modules/safenetworkjs/src/safenetwork-api.js:0:0)
    at RootHandler.initRootContainer (/snapshot/safenetwork-fuse/src/safe-vfs/root.js:0:0)
    at new RootHandler (/snapshot/safenetwork-fuse/src/safe-vfs/root.js:0:0)
    at SafeVfs.mountContainer (/snapshot/safenetwork-fuse/src/safe-vfs/index.js:0:0)
    at safeJsApi.bootstrap.then.safeVfs.mountFuse.then._ (/snapshot/safenetwork-fuse/bin.js:0:0)
    at <anonymous>
(node:3455) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:3455) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3455) UnhandledPromiseRejectionWarning: Error: SafeContainer initialise failed: _publicNames (Cannot read property 'getContainer' of undefined)
    at PublicNamesContainer.initialise (/snapshot/safenetwork-fuse/node_modules/safenetworkjs/src/safe-containers.js:0:0)
    at SafenetworkApi.getSafeContainer (/snapshot/safenetwork-fuse/node_modules/safenetworkjs/src/safenetwork-api.js:0:0)
    at RootHandler.initRootContainer (/snapshot/safenetwork-fuse/src/safe-vfs/root.js:0:0)
    at new RootHandler (/snapshot/safenetwork-fuse/src/safe-vfs/root.js:0:0)
    at SafeVfs.mountContainer (/snapshot/safenetwork-fuse/src/safe-vfs/index.js:0:0)
    at safeJsApi.bootstrap.then.safeVfs.mountFuse.then._ (/snapshot/safenetwork-fuse/bin.js:0:0)
    at <anonymous>
(node:3455) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
(node:3455) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'gt' of undefined
    at module.exports.statfs.safeVfs.getHandler.statfs.then (/snapshot/safenetwork-fuse/src/fuse-operations/statfs.js:0:0)
    at <anonymous>
(node:3455) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
```

It mounts `/dev/fuse on /home/bartek/SAFE type fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)`, but `ls /home/bartek` and `ls /home/bartek/SAFE` hang. After I kill `mount_safe`, listing these directories ends with an error `ls: cannot access '/home/bartek/SAFE': Transport endpoint is not connected` and I have to `sudo umount /home/bartek/SAFE`.

**Comment by happybeing** [comment]
Thanks again for the report - sorry it is still not working for you.

Can you just confirm you followed the steps in the Dev forum post. An I right to assume you had Peruse 0.7 running, logged into your account?

Did you see any request to give access to SAFE FUSE in the browser? I suspect not.

I'm having a similar but slightly different error with a build on a different branch, so these reports all help us home in on the issues and are very useful. I won't be able to look into it much for a few days now, but will get onto it as soon as I can. 

On 14 September 2018 19:12:21 BST, Bartosz Marcinkowski <notifications@github.com> wrote:
>I fails differently now
>
>```
>$ ./mount-safe 
>Server path not specified, so defaulting to ipc.config.socketRoot +
>ipc.config.appspace + ipc.config.id /tmp/app.3455
>starting server on  /tmp/app.3455 
>starting TLS server false
>starting server as Unix || Windows Socket
>## socket connection to server detected ##
>received event of :  auth-uri { id: '3455-cli',
>message:
>'safe-c2fmzw5ldhdvcmstznvzzq:AQAAAARkBfsAAAAAAAAAACAAAAAAAAAABqqm-pcNmgBEcgxVOasl1ryJU5Y_Oln1WWhXjrHiV88gAAAAAAAAAB5dIGphLDQNf0FQ0HT4JLRxtG9cy3xu4kaWKbOD8pZjIAAAAAAAAADefEPn_b9K0uL9Y-zDUVDVJgrcano8Ry8LjajAcWyDkkAAAAAAAAAAHGqeWoEedqG8NPbMRdoi4_hvimMp4jsh9mG7smQPPyjefEPn_b9K0uL9Y-zDUVDVJgrcano8Ry8LjajAcWyDkiAAAAAAAAAAcuE-ns3WzZ3nl0X2zf0tLJF-Zhusf7uWpT_dFJDJHXcgAAAAAAAAAFKhqh7zZROqcxVVuW99l1i7-je85dremyKSB36yKEIBAAAAAAAAAAAAAAAAAAAAAOtGsK0Epia4pp8f8ihdxcOl9MEE9whHX95vm1OtxC8hmDoAAAAAAAAYAAAAAAAAAJf1GHO_7fnqj4IuRP7OOKF_QxosPkIojQIAAAAAAAAADAAAAAAAAABfcHVibGljTmFtZXPHzemCA7eYygVC5zmwjao54Q0rBQ5pso1jQIGH2MTUAJg6AAAAAAAAASAAAAAAAAAARKNpBxBKSl9ez_BdEam5qibFLkS5Jm4a2eyO6KvQcAoYAAAAAAAAABqiSCPJYjv7wcO51e-fchm7XlUXg5bwIQAEAAAAAAAAAAAAAAABAAAAAgAAAAMAAAAHAAAAAAAAAF9wdWJsaWOixDS2iKEqhlWp5oUJt-iI8yv66pibaDrhv-kpSXnsf5g6AAAAAAAAAAAEAAAAAAAAAAAAAAABAAAAAgAAAAMAAAA'
>}
>socket disconnected 3455-cli
>(node:3455) UnhandledPromiseRejectionWarning: Error: SafeContainer
>initialise failed: _public (Cannot read property 'getContainer' of
>undefined)
>at PublicContainer.initialise
>(/snapshot/safenetwork-fuse/node_modules/safenetworkjs/src/safe-containers.js:0:0)
>at SafenetworkApi.getSafeContainer
>(/snapshot/safenetwork-fuse/node_modules/safenetworkjs/src/safenetwork-api.js:0:0)
>at RootHandler.initRootContainer
>(/snapshot/safenetwork-fuse/src/safe-vfs/root.js:0:0)
>at new RootHandler
>(/snapshot/safenetwork-fuse/src/safe-vfs/root.js:0:0)
>at SafeVfs.mountContainer
>(/snapshot/safenetwork-fuse/src/safe-vfs/index.js:0:0)
>at safeJsApi.bootstrap.then.safeVfs.mountFuse.then._
>(/snapshot/safenetwork-fuse/bin.js:0:0)
>    at <anonymous>
>(node:3455) UnhandledPromiseRejectionWarning: Unhandled promise
>rejection. This error originated either by throwing inside of an async
>function without a catch block, or by rejecting a promise which was not
>handled with .catch(). (rejection id: 4)
>(node:3455) [DEP0018] DeprecationWarning: Unhandled promise rejections
>are deprecated. In the future, promise rejections that are not handled
>will terminate the Node.js process with a non-zero exit code.
>(node:3455) UnhandledPromiseRejectionWarning: Error: SafeContainer
>initialise failed: _publicNames (Cannot read property 'getContainer' of
>undefined)
>at PublicNamesContainer.initialise
>(/snapshot/safenetwork-fuse/node_modules/safenetworkjs/src/safe-containers.js:0:0)
>at SafenetworkApi.getSafeContainer
>(/snapshot/safenetwork-fuse/node_modules/safenetworkjs/src/safenetwork-api.js:0:0)
>at RootHandler.initRootContainer
>(/snapshot/safenetwork-fuse/src/safe-vfs/root.js:0:0)
>at new RootHandler
>(/snapshot/safenetwork-fuse/src/safe-vfs/root.js:0:0)
>at SafeVfs.mountContainer
>(/snapshot/safenetwork-fuse/src/safe-vfs/index.js:0:0)
>at safeJsApi.bootstrap.then.safeVfs.mountFuse.then._
>(/snapshot/safenetwork-fuse/bin.js:0:0)
>    at <anonymous>
>(node:3455) UnhandledPromiseRejectionWarning: Unhandled promise
>rejection. This error originated either by throwing inside of an async
>function without a catch block, or by rejecting a promise which was not
>handled with .catch(). (rejection id: 5)
>(node:3455) UnhandledPromiseRejectionWarning: TypeError: Cannot read
>property 'gt' of undefined
>at module.exports.statfs.safeVfs.getHandler.statfs.then
>(/snapshot/safenetwork-fuse/src/fuse-operations/statfs.js:0:0)
>    at <anonymous>
>(node:3455) UnhandledPromiseRejectionWarning: Unhandled promise
>rejection. This error originated either by throwing inside of an async
>function without a catch block, or by rejecting a promise which was not
>handled with .catch(). (rejection id: 6)
>```
>
>It mounts `/dev/fuse on /home/bartek/SAFE type fuse
>(rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)`, but `ls
>/home/bartek` and `ls /home/bartek/SAFE` hang. After I kill
>`mount_safe`, listing these directories ends with an error `ls: cannot
>access '/home/bartek/SAFE': Transport endpoint is not connected` and I
>have to `sudo umount /home/bartek/SAFE`.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/theWebalyst/safenetwork-fuse/issues/3#issuecomment-421441114

-- 
Helping decentralise the Internet with:
  SAFE Network - Secure Access For Everyone, http://maidsafe.net
  Project Solid - Tim Berners-Lee's vision of the Web

**Comment by bm371613** [comment]
Yes I had Persue 0.7 running, I was logged in. The first time I tried to run `mount_safe`, Persue popped up with the request, which I accepted. Then I noticed errors in the logs, I unmounted the FS and tried again. Persue was still running, but there was no request, which is as expected I suppose. I pasted output of the second run.

Side note: I was happy to see the request open in Persue, when I tried safe mail tutorial / web hosting manager, it opened Firefox at `http://www.safe-auth.com//...`. :+1: for this behaviour!

**Comment by happybeing** [comment]
OK, if you can you could gather some more information it might help.

If you again log into your SAFE account, you can capture some debug info with this command:

`DEBUG=safe-fuse*,safenetworkjs* ./mount-safe 2>&1 | tee   test.log`

Try `ls ~/SAFE` then `pkill mount-safe`

Then upload the `test.log` file here. 


On 14 September 2018 19:42:54 BST, Bartosz Marcinkowski <notifications@github.com> wrote:
>Yes I had Persue 0.7 running, I was logged in. The first time I tried
>to run `mount_safe`, Persue popped up with the request, which I
>accepted. Then I noticed errors in the logs, I unmounted the FS and
>tried again. Persue was still running, but there was no request, which
>is as expected I suppose. I pasted output of the second run.
>
>Side note: I was happy to see the request open in Persue, when I tried
>safe mail tutorial / web hosting manager, it opened Firefox at
>`http://www.safe-auth.com//...`. :+1: for this behaviour!
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/theWebalyst/safenetwork-fuse/issues/3#issuecomment-421449463

-- 
Helping decentralise the Internet with:
  SAFE Network - Secure Access For Everyone, http://maidsafe.net
  Project Solid - Tim Berners-Lee's vision of the Web

**Comment by bm371613** [comment]
`ls ~/SAFE` hung again. Here is [test.log](https://github.com/theWebalyst/safenetwork-fuse/files/2384615/test.log).

**Comment by happybeing** [comment]
Thanks for the log. It is similar to an error that I have with the `development` branch (based on safe_node_app v0.9.1), so I will investigate that get back to you when I think I have something worth trying. v0.1.0 is based on branch `dev-safenodeapp-v8` which uses safe_node_app v0.8.1 and is working for most people.

Your problem may just be a dependency issue because @b-zee has this working on Arch, but he's using `fuse2` like you so I don't know what it might be for now.

Thanks for your help.

**Comment by happybeing** [comment]
Update for anyone seeing this kind of issue on Linux, please check the [dependencies](https://github.com/theWebalyst/safenetwork-fuse#31-linux) against your distro.

**Comment by happybeing** [comment]
Much has changed so it would be good to try this again with latest SAFE Drive and SAFE Browser v11.1 (or later).

SAFE Drive has a [new repo](https://github.com/theWebalyst/safe-drive), so if you do test this again, please open a new issue there. Closing this now.
